### PR TITLE
Improve s:print_stderr and make it available as vader#print_stderr

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/junegunn/vader.vim/pull/72#issuecomment-220209831

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks, but I don't see a reason to expose `s:print_stderr` as an autoload function. Care to explain why?

**Comment by junegunn** [comment]
Other than that, looks good to me.

**Comment by blueyed** [comment]
I found it to be very useful when debugging tests.

**Comment by junegunn** [comment]
How about using `Log` command? `Log getline(1, '$')` is something I use pretty often.

**Comment by blueyed** [comment]
Good point.  Amended.

**Comment by junegunn** [comment]
Thanks!

**Comment by blueyed** [comment]
@junegunn 
Damn, it does not work in Vim, and also requires the `--headless` argument with Neovim anyway.

In Vim it works using "silent ex mode":

    vim -es -c 'call writefile(["foo", "bar"], "/dev/stderr", "a")' -c q

For both Vim and Neovim it can be redirected to a file however:

    vim -c 'call writefile(["foo", "bar"], "/dev/stderr", "a")' -c q 2>/tmp/f

I'd say to remove the use-stderr-as-file again?!

**Pull request merged**
