### PR TITLE
Update document (#160)

### PR DESCRIPTION
**Pull request by cgsdfc**
Add test for #160

### CODE REVIEW

**Comment by blueyed** [comment]
I think this can be improved/detected in Vader by looking at `v:throwpoint`: if it is `function vader#assert#throws, line 5` then it means it's an undefined variable etc.

```vim
if v:throwpoint ==# 'function vader#assert#throws, line 5'
  throw 'Vader: unexpected exception: ' . v:exception
endif
```

Not sure if there is a use case for anything to throw directly from `exp`?!

**Comment by blueyed** [comment]
I think tests should go with the ones in test/feature/suite1.vader (`AssertThrows`) then, too.

**Comment by blueyed** [comment]
btw: adding `AssertException` might make sense: https://github.com/junegunn/vader.vim/issues/163

**Comment by cgsdfc** [comment]
Yes the newly added test should go into test/feature/suite1.vader. I will fix that later.

**Comment by blueyed** [comment]
Hmm, you seem to mix different issues in this PR now - please keep them separate.
What do you think about https://github.com/junegunn/vader.vim/pull/162#issuecomment-390411401?
I think we could actually fix this, instead of documenting the current behavior.

**Comment by cgsdfc** [comment]
@blueyed  You are right.  Plus I decreased code coverage, which made me close this PR.

**Comment by blueyed** [comment]
@cgsdfc 
Do you feel like creating a PR trying to fix this then instead?

**Comment by cgsdfc** [comment]
No, sorry. I have used the explicit prefix way in all my code. Although it is annoying, I have got used to it. Sorry, but really lack a motivation for me :cry:

**Pull request closed without merging**
