### PR TITLE
doc: clarify that After runs before Then

### PR DESCRIPTION
**Pull request by blueyed**
Please verify that this is correct - I had this patch from a while ago laying around.

### CODE REVIEW

**Comment by junegunn** [comment]
Yes, it's correct. But to be honest the behavior was not well thought through. I can imagine one would want `Then` to run before `After` block if `After` is used for cleaning up stuff. OTOH, if `After` is used to run code that should be repeated across test cases, then running it before `Then` makes sense. What do you think is more appropriate? Changing the order will break backward compatibility, but the order has not been documented, so we can consider that.

**Comment by blueyed** [comment]
I am not sure what is appropriate, but expected it to run after all tests.
That's why I've felt that it needs to be documented..

I am not using `Then` myself, and can totally see that it might make sense to run `After` before it, so we could skip breaking backward compatibility on this one? :)

**Comment by junegunn** [comment]
> expected it to run after all tests.

I also think that the behavior is not straightforward. I noticed it while fixing #78 you reported and realized that I didn't think through. If running `After` "after" everything else makes more sense, it's our last chance to make it right as it's not cleary documented :) I'll try to search for the tests written in Vader on GitHub, and see if there's possibility of breaking anything.

**Comment by junegunn** [comment]
I couldn't find any instance of possible breaking in plugins listed on the wiki.

However, `After` is also run before `Expect` check. The order enables/encourages putting plugin code in `After` block for manipulating the text before `Expect` check, which seems to be useful. Hmm.

**Comment by junegunn** [comment]
But no one yet seems to use it that way, so I'm leaning towards changing the execution order so that `After` is run truly after everything else. What do you think?

**Comment by blueyed** [comment]
> I'm leaning towards changing the execution order so that `After` is run truly after everything else.

Makes sense!

**Pull request closed without merging**
